favicon: /img/favicon.ico
avatar: /img/avatar.png
katex: true
force_https: true
check_update: true
word_count: true
fancybox: true

menus:
  - name: 首页
    link: /
  - name: 归档
    link: /archives/
  - name: 标签
    link: /tags/
  - name: 友链
    link: /friends/
  - name: 关于
    link: /about/
  # - name: 工具
  #   link: /box/
  #   target: _blank
  # - name: 开往
  #   link: https://travellings.link
  #   target: _blank
  - name: 开往
    picture: https://cdn.itbob.cn/img/travelling.gif
    picture_height: 25px
    picture_width: auto
    alt: 开往-友链接力
    link: https://travellings.link
    target: _blank
post:
  feature: true
disqus:
  enable: false
  shortname: 'Your shortname here'
  api: 'Your api here'
  apikey: 'Your api key here'
  admin: 'Your disqus username here'
gitalk:
  enable: true
  clientId: d19a84b9d9a2ddb2c6b9
  clientSecret: cec9feae5129a6106edc68ce06d167be8eb06021
  repository: trhx.github.io
  owner: TRHX
valine:
  enable: false
  appId: 'Your appID here'
  appKey: 'Your appKey here'
  placeholder: 'Your placeholder here'
  pageSize: 10
web_analytics:
  enable: true
  google: 
  baidu: 6ca34ddce088f8434f3c7509576819f2
footer:
rss: /atom.xml
friends:
  - name: hojun
    link: https://www.hojun.cn/
    logo: https://cdn.itbob.cn/img/friends/hojun.jpg
    description: "一个好奇的博客"
  - name: xaoxuu
    link: https://xaoxuu.com/
    logo: https://cdn.itbob.cn/img/friends/xaoxuu.jpg
    description: "iOS 开发"
  - name: ShanSan
    link: https://shan333.cn/
    logo: https://cdn.itbob.cn/img/friends/shansan.jpg
    description: "Cloud Native、DevOps"
  - name: 伊成博客
    link: https://www.devcheng.net/
    logo: https://cdn.itbob.cn/img/friends/devcheng.jpg
    description: "Java 开发"
  - name: 一个薄荷
    link: https://abohe.cn/
    logo: https://cdn.itbob.cn/img/friends/abohe.png
    description: "新媒体运营"
  - name: 煎饼果子
    link: https://blog.moej.cn/
    logo: https://cdn.itbob.cn/img/friends/moej.jpg
    description: "Vue、Spring"
  - name: 暗影
    link: https://dsanying.gitee.io/
    logo: https://cdn.itbob.cn/img/friends/dsanying.jpg
    description: "算法"
  - name: 刘向洋
    link: https://liuxiangyang.space/
    logo: https://cdn.itbob.cn/img/friends/liuxiangyang.jpg
    description: "运维"
  - name: 过客～励む
    link: https://yafine-blog.cn/
    logo: https://cdn.itbob.cn/img/friends/yafine-blog.jpg
    description: "全栈开发工程师"
  - name: Emil's blog
    link: https://blog.hvnobug.com/
    logo: https://cdn.itbob.cn/img/friends/hvnobug.jpg
    description: "Java 后台、前端 web、小程序"
  - name: 覃浩的博客
    link: https://www.imqinhao.cn/
    logo: https://cdn.itbob.cn/img/friends/imqinhao.jpg
    description: "爬虫、后端开发"
  - name: R 喵呜的小窝
    link: https://rshow.top/
    logo: https://cdn.itbob.cn/img/friends/rshow.jpg
    description: "FE Node"
  - name: HCLonely
    link: https://blog.hclonely.com/
    logo: https://cdn.itbob.cn/img/friends/hclonely.jpg
    description: "JavaScript"
  - name: Skykguj's Blog
    link: https://blog.sky390.cn/
    logo: https://cdn.itbob.cn/img/friends/sky390.jpg
    description: "OIer、软件开发者"
  - name: 番茄酱の萌化小屋
    link: https://i.kurumi.ink/
    logo: https://cdn.itbob.cn/img/friends/kurumi.png
    description: "Python Web 后端、JavaScript Web 前端"
  - name: LOVE109❤️纪实小屋
    link: https://www.love109.cn/
    logo: https://cdn.itbob.cn/img/friends/love109.jpg
    description: "记录爱情❤️记录生活"
  - name: 两个有意思的
    link: https://dxq520.cn/
    logo: https://cdn.itbob.cn/img/friends/dxq520.png
    description: "小小酥和小可爱的情侣博客"
  # - name: 神奈川上の星月夜
  #   link: https://blog.yinuxy.com/
  #   logo: https://fastly.jsdelivr.net/gh/TRHX/ImageHosting/ITRHX-LINKS/yinuxy.jpg
  #   description: "理想的生活就是生活的理想"
  # - name: 一去二三遥
  #   link: https://www.moonster.life/
  #   logo: https://fastly.jsdelivr.net/gh/TRHX/ImageHosting/ITRHX-LINKS/moonster.jpg
  #   description: "一个想当摄影师却被迫写代码的厨子"
  # - name: attack204
  #   link: https://attack204.com/
  #   logo: https://fastly.jsdelivr.net/gh/TRHX/ImageHosting/ITRHX-LINKS/attack204.jpg
  #   description: "自为风月马前卒"
  # - name: 我爱吃土豆
  #   link: https://itudo.cn/
  #   logo: https://fastly.jsdelivr.net/gh/TRHX/ImageHosting/ITRHX-LINKS/wangzhijuno.png
  #   description: "一个爱吃土豆的程序员"
  # - name: 洛尘曦
  #   link: https://www.sgyzyun.club/
  #   logo: https://fastly.jsdelivr.net/gh/TRHX/ImageHosting/ITRHX-LINKS/sgyzyun.jpg
  #   description: "一个手无缚机(手机)之力的书生小站"
  # - name: ChrAlpha
  #   link: https://blog.ichr.me/
  #   logo: https://fastly.jsdelivr.net/gh/TRHX/ImageHosting/ITRHX-LINKS/chralpha.jpg
  #   description: "你必须拼尽全力,才能显得毫不费力"
  # - name: 答案
  #   link: https://www.aquestian.cn/
  #   logo: https://fastly.jsdelivr.net/gh/TRHX/ImageHosting/ITRHX-LINKS/aquestian.gif
  #   description: "答案"
  # - name: HERMITLEE
  #   link: https://www.hermitlsr.top/
  #   logo: https://fastly.jsdelivr.net/gh/TRHX/ImageHosting/ITRHX-LINKS/hermitlsr.jpg
  #   description: "道阻且长,行则将至"
