favicon: /img/favicon.ico
avatar: /img/avatar.png
katex: true
force_https: true
check_update: true
word_count: true
fancybox: true

menus:
  - name: 首页
    link: /
  - name: 归档
    link: /archives/
  - name: 标签
    link: /tags/
  - name: 友链
    link: /friends/
  - name: 虫盒
    link: https://spiderbox.cn/
    target: _blank
  - name: 虫术
    link: https://spiderapi.cn/
    target: _blank
  - name: 关于
    link: /about/
  # - name: 工具
  #   link: /box/
  #   target: _blank
  # - name: 开往
  #   link: https://www.travellings.cn/go.html
  #   target: _blank
  - name: 开往
    picture: https://cdn.itbob.cn/img/travelling.gif
    picture_height: 25px
    picture_width: auto
    alt: 开往-友链接力
    link: https://www.travellings.cn/go.html
    target: _blank
post:
  feature: true
disqus:
  enable: false
  shortname: 'Your shortname here'
  api: 'Your api here'
  apikey: 'Your api key here'
  admin: 'Your disqus username here'
gitalk:
  enable: false
  clientId: d19a84b9d9a2ddb2c6b9
  clientSecret: cec9feae5129a6106edc68ce06d167be8eb06021
  repository: trhx.github.io
  owner: TRHX
valine:
  enable: false
  appId: 'Your appID here'
  appKey: 'Your appKey here'
  placeholder: 'Your placeholder here'
  pageSize: 10
web_analytics:
  enable: true
  google: 
  baidu: 6ca34ddce088f8434f3c7509576819f2
footer:
rss: /atom.xml
