# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: BOB'S BLOG
subtitle: 一入 IT 深似海 从此学习无绝期
description: BOB 的个人博客；主攻 Python、爬虫、逆向、数据分析、数据可视化；记录毕生所学！
keywords: ITRHX,TRHX,ITBOB,BOB,爬虫,Python爬虫,数据分析,数据可视化,逆向,逆向安全,JS逆向,安卓逆向,Android逆向,APP逆向,Python,JavaScript
author: BOB
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.itbob.cn
# permalink: :year/:month/:day/:title/
permalink: article/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace: '    '
  wrap: false
  hljs: true
# highlight:
#   enable: false
#   line_number: false
#   auto_detect: false
#   tab_replace: ''
#   wrap: true
#   hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: pure

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repository: git@github.com:TRHX/TRHX.github.io.git
    branch: master
  - type: baidu_url_submitter

# 百度搜索
baidu_url_submit:
  count: 999                   # 提交最新的多少个链接
  host: www.itbob.cn           # 在百度站长平台中添加的域名
  token: igTjk1xBNcyfKrDX      # 秘钥
  path: baidu_urls.txt         # 文本文档的地址， 新链接会保存在此文本文档里

# https://blog.csdn.net/sinat_28394909/article/details/84956096
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
  plugins:
    - '@neilsustc/markdown-it-katex'
    # - markdown-it-abbr
    # - markdown-it-cjk-breaks
    # - markdown-it-deflist
    # - markdown-it-emoji
    # - markdown-it-footnote
    # - markdown-it-ins
    # - markdown-it-mark
    # - markdown-it-sub
    # - markdown-it-sup
    # - markdown-it-checkbox
    # - markdown-it-imsize
    # - markdown-it-expandable
  anchors:
    level: 2
    collisionSuffix: 't'
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol: ''

backup:
  type: git
  theme: pure,material
  message: Back up my blog
  repository:
    github: https://github.com/TRHX/blog-backup.git,backup
